version: "3.8"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=production
      - MONGODB_URL=${MONGODB_URL}
      - PORT=${PORT}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
